version: "3"
services:
  server:
    container_name: "RemoteDoorbell_backend"
    build: "."
    ports:
      - 8765:8765
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - database
  database:
    container_name: "RemoteDoorbell_db"
    build: "./db"
    env_file:
      db.env
    ports:
      - 5489:5432